### ISSUE TITLE
Add title and meta tags to individual webpage

### ISSUE THREAD

**Issue by nveenjain** [Cyber-Labs/cyberlabs-website-frontend#123]
**Is your feature request related to a problem? Please describe.**
Search engine optimization is incomplete without specifying unique titles, meta tags for individual pages.

**Describe the solution you'd like**
Add a separate title to each page (preferably in the format Cyber Labs|Members Page).
Meta description is also CyberLabs (for every page), this needs to be changed asap.

**Describe alternatives you've considered**
Currently, only CyberLabs is shown as the page title.

**Additional context**
NA

**Comment by ujjawaljaiswal2017** [comment]
The titles have been changed. 
I am having trouble changing the meta tags.
