### ISSUE TITLE
Replace favicon with a Cyber Labs logo having transparent background

### ISSUE THREAD

**Issue by IAmSuyogJadhav** [Cyber-Labs/cyberlabs-website-frontend#129]
The current favicon has a white background. A logo with a transparent background would look much better.
---
![Screenshot](https://user-images.githubusercontent.com/30121918/57643096-8537f980-75d6-11e9-97d3-086e046183b5.png)
The current favicon.

**Comment by ujjawaljaiswal2017** [comment]
Solved in PR #131
