### ISSUE TITLE
Create static theme source.

### ISSUE THREAD

**Issue by aayushdutt** [Cyber-Labs/cyberlabs-website-frontend#4]
### Problem description:
We need to create a static html theme first to port it to React components. It will make it easier to make components when you don't have to think about looks and just focus on the logic part.

### Solution approach description:
A static html page should be made out of every php source from the old website and should be added to the folder src/src-theme-static

**Comment by nveenjain** [comment]
better not put it in src folder, put it in backup folder instead?
