### ISSUE TITLE
Update outdated repositories

### ISSUE THREAD

**Issue by nveenjain** [Cyber-Labs/cyberlabs-website-frontend#48]
**Describe the bug**
Currently, there are some dependencies which are extremely outdated. These may result in security issues inside the project. 

**Dependencies to be updated**
- debug
- node-growl
- hoek
- lodash

**Comment by PavanGangireddy** [comment]
Shall i work on this? @nveenjain

**Comment by sebastiaanspeck** [comment]
I also wanted to take this one, but I don't find the dependencies in the project

**Comment by nveenjain** [comment]
yeah sure @PavanGangireddy, you need to update the following packages to the following versions in server directory of project.
- debug ~> 2.6.9
- growl ~> 1.10.0
- hoek ~> 4.2.1
- lodash ~> 4.17.5

**Comment by sebastiaanspeck** [comment]
Already done? I got some time to fix it

**Comment by PavanGangireddy** [comment]
ok cool @sebastiaanspeck
