### ISSUE TITLE
Restructuring and adding Members data

### ISSUE THREAD

**Issue by ujjawaljaiswal2017** [Cyber-Labs/cyberlabs-website-frontend#8]
**Problem**
Currently, the data about the members is stored in the source code directly.  Addition or modification of member data will require changing the source code. This will create problems as the club scales up.

**Solution**
The data can be stored in a JSON file(members.json) in the following format.

`{ "members": [
                      {
                       "name":  "_name_",
                       "nick": "_nickname_",
                       "year": "_Year of joining_",
                       "image": "img/large/_name_.jpg"
                     },
                      ] }      `

**Additional**
Add data about new members.

**Comment by nveenjain** [comment]
We'll use an API call to get data about members, hence, we don't need to store the data in separate file.. However for dummy data, you can use separate JSON file.
