### ISSUE TITLE
Features to be implemented

### ISSUE THREAD

**Issue by sanketsingh24** [Cyber-Labs/cyberlabs-website-frontend#96]
- Modify UI and content. [UI should have a SIDE MEi design](https://www.awwwards.com/sites/microsoft-by-the-numbers)
Ideas by @sks4903440

**Comment by aayushdutt** [comment]
Postponed
* Modify UI and content. UI should have a SIDE MEi design
* Tabs for different fields
* Change UI of about us and use some animation in FAQs

**Comment by ujjawaljaiswal2017** [comment]
Moving "see projects" at the bottom of front page projects

**Comment by AnuragGupta93** [comment]
Remove Risabh Verma from Infosec

**Comment by ujjawaljaiswal2017** [comment]
Removing NDA projects

**Comment by ujjawaljaiswal2017** [comment]
Seperating Alumuni by year

**Comment by ujjawaljaiswal2017** [comment]
Removing hover effect on front page cards

**Comment by AnuragGupta93** [comment]
* Sort according to year in members page
What does this mean? All shows shorted data on members page

**Comment by AnuragGupta93** [comment]
@ujjawaljaiswal2017 Bro, keep removing the tasks that are merged

**Comment by sanketsingh24** [comment]
@AnuragGupta93  Aayush and bani are after you guys in members page
@ujjawaljaiswal2017 ask @sks4903440  he will provide details

**Comment by nveenjain** [comment]
Also, the default text is very light in color, please make the text a bit darker. grey on white background isn't appealing to the eyes and not visible too.

**Comment by aayushdutt** [comment]
[ ] Modify UI and content. UI should have a SIDE MEi design
[ ] Separate alumni by year
[ ] Cofounders(Kriti, Prabodh) and Asst Sec.
[ ] Freshman, Sophomore (2017) on profile page
[ ] Tags for different fields
[ ] Remove bottom space in the Projects page
[ ] Change UI of about us and use some animation in FAQs
[ ] Move github icon to the top right in front page project card
[ ] Put the developer name below title with an icon
[ ] Remove hover effect on front page cards
[X] Sort according to year in members page

**Comment by nullsoni** [comment]
> Moving "see projects" at the bottom of front page projects

It was supposed to be a button - "See More Projects"

**Comment by sks4903440** [comment]
> Moving "see projects" at the bottom of front page projects

It was supposed to be a button - 'See more projects'

**Comment by sks4903440** [comment]
> Remove Risabh Verma from Infosec
> Centered the footer
> Removed contact pages and added icon to header

Add padding to the footer on management page

**Comment by ujjawaljaiswal2017** [comment]
> > Moving "see projects" at the bottom of front page projects
> 
> @ujjawaljaiswal2017 It was supposed to be a button in the center- 'See more projects'

Okay I will fix that.

**Comment by ujjawaljaiswal2017** [comment]
Font color changed

**Comment by ujjawaljaiswal2017** [comment]
> * Tags for different fields
What does this suggestion actually refer to?

**Comment by ujjawaljaiswal2017** [comment]
> * Cofounders(Kriti, Prabodh) and Asst Sec.

Do you want me to add these on the Management section or Alumni section?

**Comment by sanketsingh24** [comment]
> What does this suggestion actually refer to?

I don't remember this exactly. @AnuragGupta93 @sks4903440 

> Do you want me to add these on the Management section or Alumni section?

Management Section

**Comment by sks4903440** [comment]
Tags of related field and technology used with each project
