### ISSUE TITLE
Images will decrease in quality every time `start script` runs

### ISSUE THREAD

**Issue by nveenjain** [Cyber-Labs/cyberlabs-website-frontend#99]
**Describe the bug**
run `yarn start`, everytime image will get reduced in quality to 70% of previous, even though they are already compressed.

**To Reproduce**
run `yarn start`

**Expected behavior**
Images should not be compressed if they are already compressed.

**Desktop (please complete the following information):**
 N/A

**Additional context**
To fix change https://github.com/Cyber-Labs/cyberlabs-website-frontend/blob/master/shell.sh#L8 condition to 
`if test $W -g 300; then`

Similarly for 
https://github.com/Cyber-Labs/cyberlabs-website-frontend/blob/master/shell.sh#L19

**Comment by AnuragGupta93** [comment]
Done in PR #98
